apiVersion: adi.io.my.domain/v1alpha1
kind: Cluster
metadata:
  name: cluster-sample
spec:
  name: test-cluster
  openshiftVersion: "4.7"
  clusterNetworkCidr: 10.128.0.0/14
  clusterNetworkHostPrefix: 23
