apiVersion: adi.io.my.domain/v1alpha1
kind: NMStateConfig
metadata:
  name: mynmstateconfig
  labels:
    adi.io.my.domain/selector-nmstate-config-name: abcd
spec:
  macInterfaceMap:
    - logicalNICName: "eth0"
      macAddress: "02:00:00:80:12:14"
    - logicalNICName: "eth1"
      macAddress: "02:00:00:80:12:15"
  networkYAML: "
    interfaces:
      - name: eth0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 192.168.126.30
              prefix-length: 24
          dhcp: false
      - name: eth1
        type: ethernet
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 192.168.140.30
              prefix-length: 24
          dhcp: false
    dns-resolver:
      config:
        server:
          - 192.168.126.1
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.126.1
          next-hop-interface: eth0
          table-id: 254
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.140.1
          next-hop-interface: eth1
          table-id: 254
"