apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: assisted-installer
type: Opaque
stringData:
  pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"dXNlcjpwYXNzd29yZAo=","email":"r@r.com"}}}'
